#!/bin/sh

case "$1" in
  start)
 	echo "Starting I2C..."
  modprobe i2c-bcm2708 baudrate=150000
  modprobe i2c-dev
	;;
  stop)
	printf "Stopping I2C..."
  rmmod i2c-dev
  rmmod i2c-bcm2708  
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
